name: PHP Unit Tests

on:
  push:
    branches: [ main ]
    tags: [ '*' ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: 2,20,45 10,12 25-27 1-12/2 *

jobs:
  build:

    runs-on: ubuntu-latest
    container: devwithlando/php:8.0-fpm-2

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Install dependencies
      run: composer install --prefer-dist --no-ansi --no-interaction --no-progress

    - name: Cache composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Run test suite
      run: |
        docker-php-ext-enable xdebug
        echo 'xdebug.mode=coverage' >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
        composer test

    - name: Code Style Check
      run: |
        php ./vendor/bin/phpcs -p --extensions=php --error-severity=1 --warning-severity=8 --report-json=./tests/report/phpcs-quality-report.json `find ./src/ -type f -name '*.php'`

    - name: PHP Copy Paste Check
      run: |
        test -f phpcpd.phar || curl -L https://phar.phpunit.de/phpcpd.phar -o phpcpd.phar
        php phpcpd.phar ./src/ --log-pmd=./tests/report/phpcpd-report.xml

    - name: Security Check
      run: |
        test -f local-php-security-checker || curl -L -s https://github.com/fabpot/local-php-security-checker/releases/download/v1.0.0/local-php-security-checker_1.0.0_linux_amd64 -o local-php-security-checker
        chmod +x local-php-security-checker
        ./local-php-security-checker
